<?php

return [
    'services' => [
        [
            'id' => 'seo-optimization',
            'name' => 'Otimização SEO',
            'description' => 'Melhore o ranking do seu site nos motores de busca com técnicas avançadas de SEO.',
            'short_description' => 'Aumente sua visibilidade online com estratégias SEO comprovadas.',
            'icon' => 'heroicons:magnifying-glass-plus',
            'color' => 'primary',
            'features' => [
                'Análise completa de palavras-chave',
                'Otimização on-page e off-page',
                'Relatórios mensais de performance',
                'Acompanhamento de rankings',
                'Link building estratégico',
                'Otimização técnica do site',
            ],
            'benefits' => [
                'Aumento de 300% no tráfego orgânico',
                'Melhoria de 50% no tempo de carregamento',
                'Redução de 40% na taxa de rejeição',
            ],
            'price' => 'A partir de R$ 1.500/mês',
            'duration' => '3-6 meses para resultados',
            'popular' => true,
        ],
        [
            'id' => 'web-development',
            'name' => 'Desenvolvimento Web',
            'description' => 'Sites e aplicações web modernas, responsivas e otimizadas para conversão.',
            'short_description' => 'Desenvolvimento de sites profissionais com foco em resultados.',
            'icon' => 'heroicons:code-bracket',
            'color' => 'success',
            'features' => [
                'Design responsivo e moderno',
                'Otimização para conversão',
                'Integração com sistemas',
                'Hospedagem e domínio incluídos',
                'Suporte técnico 24/7',
                'Certificado SSL gratuito',
            ],
            'benefits' => [
                'Aumento de 200% nas conversões',
                'Redução de 60% no tempo de carregamento',
                'Melhoria de 80% na experiência do usuário',
            ],
            'price' => 'A partir de R$ 3.000',
            'duration' => '2-4 semanas',
            'popular' => false,
        ],
        [
            'id' => 'digital-marketing',
            'name' => 'Marketing Digital',
            'description' => 'Estratégias completas de marketing digital para aumentar suas vendas.',
            'short_description' => 'Campanhas que geram resultados reais para seu negócio.',
            'icon' => 'heroicons:megaphone',
            'color' => 'warning',
            'features' => [
                'Gestão de redes sociais',
                'Campanhas no Google Ads',
                'Marketing de conteúdo',
                'Email marketing',
                'Analytics e relatórios',
                'Remarketing estratégico',
            ],
            'benefits' => [
                'Aumento de 400% no ROI',
                'Redução de 30% no custo por aquisição',
                'Melhoria de 150% no engajamento',
            ],
            'price' => 'A partir de R$ 2.500/mês',
            'duration' => 'Resultados em 30 dias',
            'popular' => false,
        ],
        [
            'id' => 'content-creation',
            'name' => 'Criação de Conteúdo',
            'description' => 'Conteúdo relevante e otimizado que engaja sua audiência e gera conversões.',
            'short_description' => 'Conteúdo que converte e engaja sua audiência.',
            'icon' => 'heroicons:document-text',
            'color' => 'info',
            'features' => [
                'Blog posts otimizados para SEO',
                'Vídeos e infográficos',
                'E-books e whitepapers',
                'Newsletters personalizadas',
                'Conteúdo para redes sociais',
                'Copywriting persuasivo',
            ],
            'benefits' => [
                'Aumento de 250% no tráfego orgânico',
                'Melhoria de 180% no engajamento',
                'Redução de 45% no custo de aquisição',
            ],
            'price' => 'A partir de R$ 800/mês',
            'duration' => 'Conteúdo semanal',
            'popular' => false,
        ],
        [
            'id' => 'analytics-consulting',
            'name' => 'Consultoria em Analytics',
            'description' => 'Análise de dados para otimizar suas estratégias e aumentar resultados.',
            'short_description' => 'Transforme dados em insights acionáveis.',
            'icon' => 'heroicons:chart-bar-square',
            'color' => 'secondary',
            'features' => [
                'Configuração do Google Analytics',
                'Relatórios personalizados',
                'Análise de comportamento do usuário',
                'Otimização de conversão',
                'A/B testing',
                'Dashboards executivos',
            ],
            'benefits' => [
                'Aumento de 120% na conversão',
                'Redução de 35% na taxa de abandono',
                'Melhoria de 200% no ROI',
            ],
            'price' => 'A partir de R$ 1.200/mês',
            'duration' => 'Relatórios mensais',
            'popular' => false,
        ],
        [
            'id' => 'social-media',
            'name' => 'Gestão de Redes Sociais',
            'description' => 'Presença profissional nas redes sociais que fortalece sua marca.',
            'short_description' => 'Construa uma presença digital forte e engajada.',
            'icon' => 'heroicons:share',
            'color' => 'error',
            'features' => [
                'Gestão completa de redes sociais',
                'Criação de conteúdo visual',
                'Campanhas patrocinadas',
                'Monitoramento de menções',
                'Relatórios de performance',
                'Estratégia de crescimento',
            ],
            'benefits' => [
                'Aumento de 300% no engajamento',
                'Crescimento de 150% nos seguidores',
                'Melhoria de 200% no alcance orgânico',
            ],
            'price' => 'A partir de R$ 1.800/mês',
            'duration' => 'Gestão contínua',
            'popular' => false,
        ],
    ],
    
    'categories' => [
        'seo' => [
            'name' => 'SEO e Otimização',
            'description' => 'Serviços focados em melhorar o ranking e visibilidade online',
            'icon' => 'heroicons:magnifying-glass-plus',
        ],
        'development' => [
            'name' => 'Desenvolvimento',
            'description' => 'Criação de sites e aplicações web profissionais',
            'icon' => 'heroicons:code-bracket',
        ],
        'marketing' => [
            'name' => 'Marketing Digital',
            'description' => 'Estratégias para aumentar vendas e engajamento',
            'icon' => 'heroicons:megaphone',
        ],
        'content' => [
            'name' => 'Conteúdo',
            'description' => 'Criação de conteúdo relevante e otimizado',
            'icon' => 'heroicons:document-text',
        ],
        'analytics' => [
            'name' => 'Analytics',
            'description' => 'Análise de dados e otimização de performance',
            'icon' => 'heroicons:chart-bar-square',
        ],
        'social' => [
            'name' => 'Redes Sociais',
            'description' => 'Gestão profissional de redes sociais',
            'icon' => 'heroicons:share',
        ],
    ],
    
    'testimonials' => [
        [
            'name' => 'Carlos Silva',
            'company' => 'TechStart',
            'role' => 'CEO',
            'content' => 'O serviço de SEO transformou completamente nossa presença online. Em 3 meses, nosso tráfego orgânico aumentou 400%.',
            'rating' => 5,
            'service' => 'seo-optimization',
        ],
        [
            'name' => 'Ana Costa',
            'company' => 'E-commerce Plus',
            'role' => 'Diretora de Marketing',
            'content' => 'O site desenvolvido pela equipe superou todas as expectativas. Nossas conversões aumentaram 250% no primeiro mês.',
            'rating' => 5,
            'service' => 'web-development',
        ],
        [
            'name' => 'Roberto Lima',
            'company' => 'Digital Solutions',
            'role' => 'Fundador',
            'content' => 'A estratégia de marketing digital implementada gerou um ROI de 500% em apenas 6 meses. Resultados excepcionais!',
            'rating' => 5,
            'service' => 'digital-marketing',
        ],
    ],
    
    'faq' => [
        [
            'question' => 'Quanto tempo leva para ver resultados?',
            'answer' => 'Os resultados variam conforme o serviço. SEO leva 3-6 meses, marketing digital mostra resultados em 30 dias, e desenvolvimento web fica pronto em 2-4 semanas.',
        ],
        [
            'question' => 'Vocês oferecem suporte após a entrega?',
            'answer' => 'Sim! Todos os nossos serviços incluem suporte técnico e acompanhamento contínuo para garantir que você obtenha os melhores resultados.',
        ],
        [
            'question' => 'Como funciona o processo de contratação?',
            'answer' => 'Iniciamos com uma consultoria gratuita para entender suas necessidades, depois apresentamos uma proposta personalizada com cronograma e investimento.',
        ],
        [
            'question' => 'Vocês trabalham com empresas de qualquer tamanho?',
            'answer' => 'Sim! Atendemos desde startups até grandes corporações, adaptando nossas estratégias às necessidades e orçamento de cada cliente.',
        ],
        [
            'question' => 'Quais são as formas de pagamento?',
            'answer' => 'Aceitamos PIX, transferência bancária, cartão de crédito e parcelamento. Para projetos maiores, oferecemos condições especiais.',
        ],
    ],
]; 